"""Application workflow for creating AI mapping proposals from source files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from collections.abc import Awaitable, Callable
from typing import Any

from src.application.mapping.errors import MappingValidationError
from src.core.enums import FileType
from src.domain.mapping.contract import canonicalize_field_mappings, serialize_field_mappings
from src.domain.mapping.models import MappingConfig, MappingConfigStatus
from src.domain.review.models import (
    CopilotAction,
    CopilotActionStatus,
    CopilotActionType,
    ReviewPacket,
    ReviewPacketSourceType,
)


@dataclass(frozen=True)
class CreateMappingProposalCommand:
    partner: str
    source_file_path: Path
    source_type: str = ReviewPacketSourceType.UPLOAD.value
    source_file: Any = None
    reconciliation_date: Any = None


@dataclass(frozen=True)
class MappingProposalResult:
    response: dict[str, Any]
    proposal: MappingConfig
    action: CopilotAction
    packet: ReviewPacket


class MappingProposalService:
    """Build the pending mapping, copilot action, and review packet together."""

    def __init__(
        self,
        *,
        mapping_repo,
        action_repo,
        review_packet_repo,
        signature_builder: Callable[[Path], Any],
        config_generator: Callable[..., Awaitable[tuple[dict[str, Any] | None, str | None]]],
        scope_classifier: Callable[..., Awaitable[dict[str, Any]]],
    ) -> None:
        self.mapping_repo = mapping_repo
        self.action_repo = action_repo
        self.review_packet_repo = review_packet_repo
        self.signature_builder = signature_builder
        self.config_generator = config_generator
        self.scope_classifier = scope_classifier

    async def create_from_source_file(
        self,
        command: CreateMappingProposalCommand,
    ) -> MappingProposalResult:
        signature = self.signature_builder(command.source_file_path)
        if not signature.headers:
            raise MappingValidationError("Uploaded file is empty.")

        config_dict, error = await self.config_generator(
            partner=command.partner,
            headers=signature.headers,
            sample_rows=signature.sample_rows,
            known_constants={"provider": command.partner},
            header_row_index=signature.header_row_index,
            first_data_row_index=signature.first_data_row_index,
        )
        if error or config_dict is None:
            raise MappingValidationError(f"AI mapping generation failed: {error}")

        field_mappings, mapping_warnings = canonicalize_field_mappings(
            serialize_field_mappings(config_dict.get("fieldMappings") or [])
        )
        version = await self.mapping_repo.allocate_next_version(command.partner)
        confidence = config_dict.get("confidence") or 0.85
        reasoning = config_dict.get("reasoning") or "Automatically generated by AI."
        proposal = MappingConfig(
            partner=command.partner,
            workflowType="UPC",
            fileType=FileType.SETTLEMENT,
            sheetName=config_dict.get("sheetName") or "Sheet1",
            startRow=config_dict.get("startRow") or 2,
            fieldMappings=field_mappings,
            configVersion=version,
            structureSignature=signature.to_dict(),
            status=MappingConfigStatus.PENDING_APPROVAL,
            configHealth={
                "stale": False,
                "status": MappingConfigStatus.PENDING_APPROVAL.value,
                "confidence": confidence,
                "reasoning": reasoning,
            },
        )
        await self.mapping_repo.create(proposal)

        action = CopilotAction(
            type=CopilotActionType.MAPPING_PROPOSAL,
            status=CopilotActionStatus.PENDING_APPROVAL,
            partner=command.partner,
            workflowType="UPC",
            fileType=FileType.SETTLEMENT,
            draftMappingId=str(proposal.id),
            payload={
                "proposedMappings": field_mappings,
                "sheetName": proposal.sheet_name,
                "startRow": proposal.start_row,
                "confidence": confidence,
                "reasoning": reasoning,
                "headers": signature.headers,
                "sampleRows": signature.sample_rows[:10],
            },
            reason="Generated from source file for review",
        )
        await self.action_repo.create(action)

        active_runtime = await self.mapping_repo.find_by_partner_and_type(
            command.partner,
            "UPC",
            FileType.SETTLEMENT,
        )
        scope_meta = await self.scope_classifier(
            partner=command.partner,
            reconciliation_date=command.reconciliation_date,
        )
        validation_gates = [
            {
                "gateKey": "structure_signature",
                "label": "Structure signature generated",
                "status": "pass",
                "reason": "File headers and shape were fingerprinted successfully.",
            },
            {
                "gateKey": "required_fields",
                "label": "Required fields proposed",
                "status": "pass" if any(
                    mapping.get("path") in {"id", "amount", "transDate"}
                    for mapping in field_mappings
                ) else "warn",
                "reason": "AI generated canonical fields for settlement parsing.",
            },
            {
                "gateKey": "runtime_impact",
                "label": "Runtime impact assessed",
                "status": "warn",
                "reason": (
                    "Approved runtime config will be kept until reviewer decides."
                    if active_runtime
                    else "No approved runtime config exists yet."
                ),
            },
        ]
        recommended_action_type = (
            "APPROVE_AND_ACTIVATE_NEXT_RUNTIME"
            if active_runtime
            else "APPROVE_REQUIRED_BEFORE_RUNTIME"
        )
        recommended_reason = (
            "Structure changed from the currently approved runtime; use the old runtime until review completes."
            if active_runtime
            else "No approved runtime config exists, so this draft must be reviewed before ingestion can continue."
        )
        packet = ReviewPacket(
            sourceType=ReviewPacketSourceType(command.source_type),
            partner=command.partner,
            fileName=command.source_file_path.name,
            fileTypeDetected=FileType.SETTLEMENT.value,
            structureSignature=proposal.structure_signature,
            activeRuntimeConfigId=str(active_runtime.id) if active_runtime else None,
            draftMappingId=str(proposal.id),
            targetActionId=str(action.id),
            sourceFileId=str(command.source_file.id) if command.source_file is not None else None,
            sourceFilePath=str(command.source_file_path),
            scopeType=scope_meta["scopeType"],
            scopeConfidence=scope_meta["scopeConfidence"],
            scopeReason=scope_meta["scopeReason"],
            scopeSignals=scope_meta["scopeSignals"],
            recommendedAction={
                "actionType": recommended_action_type,
                "reason": recommended_reason,
                "confidence": confidence,
            },
            parseStrategy={
                "sheetName": proposal.sheet_name,
                "startRow": proposal.start_row,
                "fieldMappingCount": len(field_mappings),
                "strategy": "AI inferred spreadsheet draft mapping",
            },
            validationGates=validation_gates,
            samplePreview=[
                {"rowIndex": index + 1, "values": row}
                for index, row in enumerate(signature.sample_rows[:5])
            ],
            riskSummary={
                "severity": "high" if not active_runtime else "medium",
                "summary": recommended_reason,
            },
            runtimeDecisionHint=(
                "KEEP_CURRENT_RUNTIME_UNTIL_APPROVED"
                if active_runtime
                else "BLOCK_UNTIL_APPROVED"
            ),
        )
        await self.review_packet_repo.create(packet)

        response_config = {
            "partner": command.partner,
            "workflowType": "UPC",
            "fileType": FileType.SETTLEMENT.value,
            "sheetName": proposal.sheet_name,
            "startRow": proposal.start_row,
            "configVersion": proposal.config_version,
            "fieldMappings": field_mappings,
            "status": MappingConfigStatus.PENDING_APPROVAL.value,
            "configHealth": proposal.config_health,
        }
        confidence_scores = {
            mapping["path"]: confidence
            for mapping in field_mappings
            if mapping.get("path")
        }
        response = {
            "ok": True,
            "mapping": field_mappings,
            "confidenceScores": confidence_scores,
            "warnings": mapping_warnings,
            "suggestedConstants": [
                {
                    "path": "currency",
                    "constant": "VND",
                    "reason": "Default settlement currency",
                }
            ],
            "config": response_config,
            "configStatus": MappingConfigStatus.PENDING_APPROVAL.value,
            "draftMappingId": str(proposal.id),
            "reviewItemId": str(packet.id),
            "isRuntimeEligible": False,
            "scopeAssessment": scope_meta,
            "planSummary": {
                "sheetName": proposal.sheet_name,
                "startRow": proposal.start_row,
                "fieldMappingCount": len(field_mappings),
            },
            "headers": signature.headers,
            "sampleRows": signature.sample_rows[:10],
        }
        return MappingProposalResult(
            response=response,
            proposal=proposal,
            action=action,
            packet=packet,
        )
