export function renderAutomation({
  state,
  data,
  badge,
  escapeHtml,
  formatDisplayDateTime,
  formatNumber,
  metrics,
  severityBadge,
  table,
}) {
  const jobs = data.jobs || [];
  const runningPartners = state.automationRunningPartners || {};
  const newPacketIds = new Set(state.automationNewPacketIds || []);
  const recentPackets = jobs.flatMap(job => (job.recentPackets || []).map(packet => ({
    ...packet,
    partner: job.partner,
    fetchMethod: job.fetchMethod,
  }))).sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))).slice(0, 8);

  const resolveJobDate = job => {
    const runDate = String(job.latestRuntimeRun?.date || "").trim();
    if (runDate) return runDate;
    const fileDate = String(job.latestFile?.reconciliationDate || "").trim();
    return fileDate ? fileDate.slice(0, 10) : "";
  };

  const rows = jobs.length ? jobs.map(job => {
    const partnerKey = String(job.partner || "");
    const isRunning = Boolean(runningPartners[partnerKey]);
    return `
    <tr>
      <td><strong>${escapeHtml(job.partner || "-")}</strong></td>
      <td>${escapeHtml(job.fetchMethod || "-")}</td>
      <td><code>${escapeHtml(job.schedule || "-")}</code></td>
      <td>${escapeHtml(job.destination || "-")}</td>
      <td>
        <div style="display:flex; gap:6px; align-items:center; flex-wrap:wrap;">
          ${job.enabled ? `<span class="badge matched">Enabled</span>` : `<span class="badge critical">Disabled</span>`}
          ${badge(job.status || "HEALTHY")}
          ${job.hasPendingFile ? `<span class="badge warning">Pending file</span>` : ""}
        </div>
        <div class="muted" style="font-size:11px; margin-top:6px;">${escapeHtml(job.statusMessage || "No active runtime work.")}</div>
      </td>
      <td>
        <div style="display:flex; gap:8px; align-items:center; flex-wrap:wrap;">
          <span class="badge neutral">${formatNumber(job.pendingReviewPackets || 0)} pending packets</span>
          <button class="button secondary-action ${isRunning ? "automation-run-button-running" : ""}" data-action="run-job-now" data-partner="${escapeHtml(job.partner || "")}" ${isRunning ? "disabled" : ""}>${isRunning ? `<span class="spinner-mini" style="display:inline-block; width:12px; height:12px; border:2px solid currentColor; border-top:2px solid transparent; border-radius:50%; animation:spin 1s linear infinite; margin-right:6px; vertical-align:middle;"></span>Running...` : "Run Now"}</button>
        </div>
      </td>
    </tr>
  `;
  }).join("") : `<tr><td colspan="6" style="text-align:center; padding: 24px 0;">No enabled automation jobs found.</td></tr>`;

  return `
    ${metrics([
      ["Enabled Jobs", formatNumber(jobs.filter(job => job.enabled).length), "Scheduler-connected fetch configs"],
      ["Pending Review Items", formatNumber(jobs.reduce((sum, job) => sum + Number(job.pendingReviewPackets || 0), 0)), "Review items waiting after automation runs"],
      ["Partners Waiting", formatNumber(jobs.filter(job => job.hasPendingFile).length), "Partners with files ready but not fully reconciled"],
      ["Active Runtime Runs", formatNumber(jobs.filter(job => ["QUEUED", "FETCHING", "INGESTING", "WAITING_REVIEW", "WAITING_RECONCILE", "RECONCILING"].includes(String(job.status || "").toUpperCase())).length), "Partners currently fetching, ingesting, waiting for review, or reconciling"],
      ["Partners Covered", formatNumber(jobs.length), "Configured partner fetch routes"]
    ])}
    <section class="panel" style="margin-bottom: 24px;">
      <div class="panel-header with-icon">
        <div>
          <h2 class="section-title">Scheduler Jobs</h2>
          <p class="section-subtitle">Realtime visibility into partner fetch routes, pending files, and current runtime stages.</p>
        </div>
        <span class="material-symbols-outlined panel-header-icon">schedule</span>
      </div>
      ${table(["Partner", "Method", "Schedule", "Destination", "Runtime State", "Actions"], rows)}
    </section>
    <section class="panel">
      <div class="panel-header with-icon">
        <div>
          <h2 class="section-title">Recent Automation Review Output</h2>
          <p class="section-subtitle">Latest packets generated by automation-backed file fetches and format-drift checks.</p>
        </div>
        <span class="material-symbols-outlined panel-header-icon">smart_toy</span>
      </div>
      <div class="review-card-grid">
        ${(recentPackets.length ? recentPackets : [{
          partner: "Automation",
          fileName: "No recent packets",
          recommendedAction: { reason: "No job-created review packets are available yet." },
          riskSummary: { severity: "low" },
          _id: "",
          status: "CLEAR",
          fetchMethod: "-"
        }]).map(packet => `
          <article class="review-card ${packet._id ? "" : "empty-card"} ${packet._id && newPacketIds.has(String(packet._id)) ? "automation-packet-enter" : ""}">
            <div class="review-card-top">
              <div>
                <p class="eyebrow">${escapeHtml(packet.fetchMethod || packet.sourceType || "-")}</p>
                <h3>${escapeHtml(packet.partner || "-")}</h3>
              </div>
              ${severityBadge(packet.riskSummary?.severity || "medium")}
            </div>
            <p class="review-reason">${escapeHtml(packet.fileName || "-")}</p>
            <div class="review-meta-row">
              ${badge(packet.status || "-")}
              ${packet.sourceType ? `<span class="badge neutral">${escapeHtml(packet.sourceType)}</span>` : ""}
              ${packet.decisionMode ? `<span class="badge neutral">${escapeHtml(packet.decisionMode)}</span>` : ""}
            </div>
            <div class="review-impact-box">
              <strong>Agent recommendation</strong>
              <p>${escapeHtml(packet.recommendedAction?.reason || packet.riskSummary?.summary || "-")}</p>
            </div>
            ${packet.reviewedAt ? `<div class="muted" style="font-size:12px;">Reviewed by ${escapeHtml(packet.reviewedBy || "Administrator")} on ${escapeHtml(formatDisplayDateTime(packet.reviewedAt))}</div>` : ""}
            ${packet._id ? `<button class="button primary" data-action="go-review-packet" data-packet-id="${escapeHtml(packet._id)}" data-partner="${escapeHtml(packet.partner)}" style="margin-top: 8px; width: 100%; justify-content: center;">Open Approval Desk</button>` : ""}
          </article>
        `).join("")}
      </div>
    </section>
  `;
}
