"""Pydantic schemas for the AI Analysis Layer.

Defines the data contracts between rule-based layer and LLM layer:
- GroupCriteria: input for grouping engine
- GroupResult: output of grouping engine
- SummaryResult: aggregated stats from MetricsService
- AnalysisResult: individual insight from LLM
- AnalysisInput: full structured input contract for LLM

Contract rules:
- No raw transaction IDs (no partner_txn_id, internal_txn_id)
- No specific per-transaction amounts — only ranges and totals
- Metrics single source: summary_metrics only from MetricsService
- Grouped only: grouped_stats only from GroupingEngine
- Pre-processed: top_anomalies from rule-based filtering
- Deterministic: same input → same AnalysisInput
"""

from datetime import date
from typing import Any, Optional

from pydantic import BaseModel, Field


class GroupCriteria(BaseModel):
    """Criteria for grouping reconciliation results.

    All fields are optional — only specified criteria are applied.
    """

    status: Optional[str] = Field(default=None, description="Filter by reconciliation status")
    partner: Optional[str] = Field(default=None, description="Filter by partner identifier")
    amount_range_min: Optional[float] = Field(default=None, description="Minimum amount (inclusive)")
    amount_range_max: Optional[float] = Field(default=None, description="Maximum amount (exclusive)")
    date_from: Optional[date] = Field(default=None, description="Start date (inclusive)")
    date_to: Optional[date] = Field(default=None, description="End date (inclusive)")


class GroupResult(BaseModel):
    """Result of a grouping operation.

    Represents a cluster of reconciliation results sharing common attributes.
    """

    key: str = Field(description="Group identifier (e.g. status name, amount range)")
    count: int = Field(description="Number of results in this group")
    percentage: float = Field(description="Percentage of total results")
    total_amount: float = Field(default=0.0, description="Sum of amounts in this group")
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional group-specific details (avg_difference, min, max, etc.)",
    )


class SummaryResult(BaseModel):
    """Aggregated summary metrics for a partner on a given date.

    Single source of truth — computed by MetricsService only.
    """

    partner: str = Field(description="Partner identifier")
    date: str = Field(description="Date string (YYYY-MM-DD)")
    total_transactions: int = Field(description="Total number of reconciliation results")
    matched: int = Field(description="Count of MATCHED results")
    mismatch_rate: float = Field(description="Mismatch rate as percentage")
    total_amount_mismatch: float = Field(default=0.0, description="Total mismatched amount")
    by_status: dict[str, int] = Field(
        default_factory=dict,
        description="Count of results by reconciliation status",
    )


class AnalysisResult(BaseModel):
    """A single insight generated by the LLM analysis.

    Represents an actionable finding with severity and recommendation.
    """

    type: str = Field(description="Insight type (e.g. operational_delay, partner_pattern)")
    severity: str = Field(description="Severity level: low | medium | high | critical")
    title: str = Field(description="Short descriptive title")
    description: str = Field(description="Detailed explanation of the finding")
    affected_count: int = Field(default=0, description="Number of transactions affected")
    recommendation: str = Field(default="", description="Suggested action for operators")


class TopAnomaly(BaseModel):
    """A pre-processed anomaly for LLM analysis input.

    Rule-based filtering result — not raw transaction data.
    """

    type: str = Field(description="Anomaly type (e.g. missing_internal_batch)")
    count: int = Field(description="Number of occurrences")
    partners_affected: list[str] = Field(default_factory=list, description="Affected partners")
    amount_range: str = Field(default="", description="Amount range description (e.g. '0-100k')")


class SelectedErrorSignal(BaseModel):
    """Summarized signal derived from a bounded, selected set of error records."""

    status: str = Field(description="Reconciliation error status")
    sample_count: int = Field(description="Number of sampled records represented by this signal")
    amount_range: str = Field(default="", description="Representative amount-difference or amount band")
    pattern_hint: str = Field(default="", description="Short deterministic hint about the sampled pattern")


class AnalysisInput(BaseModel):
    """Full structured input contract for the LLM layer.

    This is the ONLY data sent to the LLM. It contains:
    - summary_metrics: aggregated stats (from MetricsService)
    - grouped_stats: cluster results (from GroupingEngine)
    - top_anomalies: rule-based pre-processed anomalies

    NEVER includes raw transaction data (IDs, specific amounts).
    """

    partner: str = Field(description="Partner identifier")
    date: str = Field(description="Date string (YYYY-MM-DD)")
    focus: str = Field(
        default="operational",
        description="Analysis focus: operational | partner | inconsistency",
    )
    summary_metrics: dict[str, Any] = Field(
        description="Aggregated summary metrics from MetricsService",
    )
    grouped_stats: list[dict[str, Any]] = Field(
        description="Grouped statistics from GroupingEngine",
    )
    top_anomalies: list[TopAnomaly] = Field(
        default_factory=list,
        description="Pre-processed anomalies (rule-based filtering)",
    )
    selected_error_signals: list[SelectedErrorSignal] = Field(
        default_factory=list,
        description="Summarized signals derived from bounded, selected error records",
    )


class AIInsight(BaseModel):
    """Structured output contract from the LLM.

    This is the validated schema for LLM JSON-mode responses.
    Replaces fragile text parsing with pydantic validation.
    """

    type: str = Field(description="Insight type (e.g. operational_delay, partner_pattern)")
    severity: str = Field(description="Severity level: low | medium | high | critical")
    title: str = Field(description="Short descriptive title")
    description: str = Field(description="Detailed explanation of the finding")
    affected_count: int = Field(default=0, description="Number of transactions affected")
    recommendation: str = Field(default="", description="Suggested action for operators")


class AIInsightResponse(BaseModel):
    """Top-level response wrapper from LLM JSON-mode output.

    The LLM returns: {"findings": [AIInsight, ...]}
    """

    findings: list[AIInsight] = Field(description="List of AI-generated insights")


class AIObservation(BaseModel):
    """Observability data collected during AI insight generation.

    Tracks latency, token usage, cost, provider info, and resolution path.
    """

    partner: str = Field(description="Partner identifier")
    date: str = Field(description="Date string (YYYY-MM-DD)")
    focus: str = Field(description="Analysis focus type")
    provider: str = Field(default="", description="Provider used (primary/fallback)")
    model: str = Field(default="", description="Model used")
    latency_ms: float = Field(default=0.0, description="Total generation latency in ms")
    prompt_tokens: int = Field(default=0, description="Input token count")
    completion_tokens: int = Field(default=0, description="Output token count")
    total_tokens: int = Field(default=0, description="Total token count")
    estimated_cost_usd: float = Field(default=0.0, description="Estimated cost in USD")
    cache_hit: bool = Field(default=False, description="Whether result came from cache")
    cache_key: str = Field(default="", description="Cache key if applicable")
    schema_valid: bool = Field(default=True, description="Whether LLM output passed schema validation")
    resolution: str = Field(
        default="llm",
        description="Resolution path: llm | llm_fallback | schema_fallback | rule_based",
    )
    guardrail_result: dict[str, Any] | None = Field(
        default=None,
        description="Guardrail validation result (is_valid, risk_level, findings)",
    )
